[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.0.4
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DFW_DEVICE_ID=\"probe-001\"
  -DWIFI_SSID=\"lol123\"
  -DWIFI_PASSWORD=\"11111111\"
  -DMQTT_HOST=\"localhost\"
  -DMQTT_PORT=1883
  -DMQTT_USER=\"\"
  -DMQTT_PASSWORD=\"\"
